#!/bin/bash
# color is an ANSI escape code, quotations or not, no matter
# refer to https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797 for help with these.

text="$1"
delay="$2"
color="$3"

if [[ "$delay" == "" ]]; then
    delay="0.025"
    color="$2"
    if [[ "$color" == "" ]]; then
	color="\033[0m"
    fi
fi
echo -e "$color"
for (( i=0; i<${#text}; i++)); do
    printf "%s" "${text:i:1}"
    sleep "$delay"
done
echo -e "\n"
